[package]
name = "egui-sdl2-event-example"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version= "0.37.0", features = ["raw-window-handle",  "bundled", "static-link"] }
egui-sdl2-event = { path = "../lib" }
egui-wgpu = "0.28.1"
egui = "0.28.1"
# wgpu = "22.0.0"
pollster = "0.2.5"



